### PR TITLE
Identifier getters now found in traits when generating proxies.

### PR DESCRIPTION
**Pull request by tPl0ch**
Related to http://www.doctrine-project.org/jira/browse/DDC-2556

TODO: Add test cases

### CODE REVIEW

**Comment by Ocramius** [comment]
Note: I'd rather NOT have trait support for this rather than adding this bunch of very fragile complexity.

Additionally, see doctrine/doctrine2#1241, which would solve this upfront.

**Comment by tPl0ch** [comment]
@Ocramius So waiting for 3.0 is the only chance of getting our traits back, am I right?

**Comment by Ocramius** [comment]
Probably, yeah... I could also accept this hotfix if accurately tested (all npaths)

**Comment by enumag** [comment]
The problem is that `ReflectionMethod::getDeclaringClass()` does not return the trait where the method was declared. In my opinion the correct solution would be to use a [helper method](https://github.com/nette/reflection/blob/master/src/Reflection/Helpers.php#L24-L32) which fixes that. This might also be relevant to some other places where `ReflectionMethod::getDeclaringClass()` is used.

**Comment by Ocramius** [comment]
Closing: the complexity of this fix, as well as the depth of the bug (touching all the weird parts of traits) are not worth fixing, IMO.

**Comment by Ocramius** [comment]
Note: not a `won't fix`, but a `can't fix`.

**Pull request closed without merging**
