### PR TITLE
Proxy\Autoloader should not be internal

### PR DESCRIPTION
**Pull request by BenMorel**
Originally reported in https://github.com/doctrine/orm/issues/8313

---

The [ORM docs on autoloading proxies](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/advanced-configuration.html#autoloading-proxies) suggest to use:

```php
<?php
use Doctrine\Common\Proxy\Autoloader;

$proxyDir = "/path/to/proxies";
$proxyNamespace = "MyProxies";

Autoloader::register($proxyDir, $proxyNamespace);
```

Even though the `Autoloader` class is `@internal`:

```
namespace Doctrine\Common\Proxy;

/**
 * @internal
 */
class Autoloader
{
```

If `Proxy\Autoloader` is really intended to be used by consumers, then it should not be internal.

### CODE REVIEW

**Review by SenseException — DISMISSED** [review]

**Comment by greg0ire** [comment]
Should this really target master? This looks more like a bugfix (for IDEs / static analysis, but still) to me.

**Comment by greg0ire** [comment]
Retargeting to 3.1.x because I need to remove master, but IMO it should be 3.0.x

**Comment by BenMorel** [comment]
@greg0ire Indeed, I rebased on `3.0.x` instead!

**Comment by greg0ire** [comment]
This should fix the build: https://twitter.com/greg0ire/status/1320417776813678593

**Comment by greg0ire** [comment]
> This should fix the build: https://twitter.com/greg0ire/status/1320417776813678593

Ah no it won't since we use coding-standard… 1 . We have to use at least 6 for this to work :facepalm:

**Comment by BenMorel** [comment]
@greg0ire Not sure what I'm supposed to do here... ;-)

**Comment by greg0ire** [comment]
Don't worry, I'm working on it, I will fix it somehow :stuck_out_tongue:

**Comment by greg0ire** [comment]
Behold #903

**Comment by SenseException** [comment]
I created #904 to adapt to the branch changes.

**Comment by greg0ire** [comment]
Travis seems stuck, let's try that again.

**Comment by BenMorel** [comment]
A lot of work for one line... ;-)

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @BenMorel !

**Pull request merged**
