### PR TITLE
Made PATTERN_MATCH_ID_METHOD more flexible

### PR DESCRIPTION
**Pull request by 4alexandr**
PATTERN_MATCH_ID_METHOD match any valid function declaration, example:
function getId(){return$this->id;}

### CODE REVIEW

**Comment by Ocramius** [comment]
@4alexandr requires test case.

**Comment by 4alexandr** [comment]
@Ocramius Sorry, i don't know, how to write tests for this change. I can test this only manually.
Old pattern can match 
```php
    public function getId()
    {
        return $this->id;
    }
```
but can't
```php
    public function getId(){
        return $this->id;
    }
```
In commit i change non-required whitespaces detection in function declaration.

**Comment by Ocramius** [comment]
@4alexandr look at existing tests for the proxy generator ;-)

**Comment by Ocramius** [comment]
Is also fixed by something like doctrine/doctrine2#1241 (linking for reference - this partial fix is fine for now)

**Comment by Ocramius** [comment]
Related (not blocking) doctrine/doctrine2#1241

**Comment by Ocramius** [comment]
Checked again, and writing a test case for this is a huge annoyance for little benefit. Merging as-is.

**Pull request merged**
