### PR TITLE
fixates dependencies to the last version that supports php 5.6

### PR DESCRIPTION
**Pull request by rnuernberg**

### CODE REVIEW

**Comment by alcaeus** [comment]
Requiring PHP 7.1 was intentional. There's no need to switch back. Closing as `invalid`.

**Comment by rnuernberg** [comment]
For every old version of doctrine? That is quite painful - may I ask why?

**Comment by Ocramius** [comment]
Older versions will install just fine: composer will resolve the latest
compatible versions for you

**Comment by rnuernberg** [comment]
@Ocramius ah sorry - my bad. My project accidentally used php 7.1 on my local machine. Once I switch it to php 5.6 it does indeed install correctly.

**Pull request closed without merging**
