### PR TITLE
Minor docblock spelling correction

### PR DESCRIPTION
**Pull request by gnat42**
Just a minor docblock typo

### CODE REVIEW

**Comment by stof** [comment]
Good catch. Thanks

**Comment by greg0ire** [comment]
Can you make a release?

**Comment by stof** [comment]
just for that ? not worth it IMO

**Comment by Soullivaneuh** [comment]
> just for that ? not worth it IMO

@stof I think this is a very very very critical issue.

Really.

:trollface:

**Comment by greg0ire** [comment]
@stof I edited my post to make the trolling obvious :P

**Comment by Ocramius** [comment]
Send critical money to my address for a release :-P

**Comment by Soullivaneuh** [comment]
@Ocramius I'm from Lille, we pay only with :beer: here.

**Comment by Ocramius** [comment]
I could probably replace lunch with beer, but my current client wouldn't approve of my behavior in the office afterwards.

**Comment by greg0ire** [comment]
> my current client

The one that forces you to work on Windows? They sound like fun!

**Pull request merged**
