### PR TITLE
Fix #751: non optional type hinted parameters pre 7.1 support

### LINKED ISSUE #751: Error in generated Entity Proxy class
I have started to get errors after updating deployed aplication.

`Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) on /app/cache/prod/doctrine/orm/Proxies/__CG__AppBundleEntityEntityName.php`

Original method

`someMethod( ClassName $inputParam)`
generated proxy

`someMethod ( ? \Full\NamespacePath\ClassName $inputParam)`
I just deleted the ? in the generated code and is working again.

Just to be sure, I re-deployed the app and I got the same issue.

Its running on Php 7.0.8. Deployed version of doctrine common is 2.7.0 (actually this started to happen after update from 2.6.1 to 2.7.0 doctrine/dbal from 2.5.5 to 2.4.5 (don't know why composer has downgraded this package)

### PR DESCRIPTION
**Pull request by Ocramius**
Fixes #751

### CODE REVIEW

**Comment by Ocramius** [comment]
@Majkl578 full ack. Can you send a PR against this branch? I'm leaving this to be merged tomorrow, so you can do what you want with the branch...

**Comment by Ocramius** [comment]
I added the tests, but cannot push because airport WiFi decided that I'm
not worthy. Will do in a bit.

**Comment by Ocramius** [comment]
Handled in #752. Now tagging 2.7.1

**Comment by Majkl578** [comment]
@Ocramius Thanks, didn't have time to do that earlier myself. :|

**Comment by Ocramius** [comment]
@Majkl578 np!

**Pull request merged**
