### PR TITLE
Run tests on PHP 7.3

### PR DESCRIPTION
**Pull request by mnapoli**

### CODE REVIEW

**Comment by mnapoli** [comment]
Ah nevermind sorry for the noise! I thought this was available (because the build showed up correctly on another project) but it isn't yet.

**Comment by Ocramius** [comment]
Will be merged when ready :+1:

**Comment by mnapoli** [comment]
For reference: https://travis-ci.org/CouscousPHP/Couscous/jobs/420526698

I was mistaken because the build appears in Travis so I thought "great!", but then the build failed…

**Comment by mnapoli** [comment]
Thanks for the link!

**Pull request closed without merging**
