### PR TITLE
Add autoload to composer.json

### PR DESCRIPTION
**Pull request by pgddevil**

### CODE REVIEW

**Comment by Ocramius** [comment]
@pgddevil we don't support `2.0.x` anymore: why are you suggesting this change here?

**Comment by pgddevil** [comment]
because I have not yet upgraded and wanted to use composer.  quite useless to have added a composer.json without tagging and without the autoload.

**Comment by pgddevil** [comment]
However I can declare the package in my own composer.json if you don't want to go further with the autoload add-on.

**Comment by fprochazka** [comment]
@pgddevil you can add the autoloader definition to autoloader section of your project and it will also work.

**Comment by pgddevil** [comment]
Well, I know I can do it another way.  I wanted to do it the clean way.  I've already fixed my situation.  It's up to you to decide to merge or not.

**Comment by Ocramius** [comment]
Yeah, you should handle autoloading yourself here.

2.0.0 is pre-composer (composer didn't even exist), and it's not a good idea to exhume a dead release.

Consider upgrading to a newer version of the library.

**Pull request closed without merging**
