### PR TITLE
JIRA is dead, long live the Github issue tracker

### PR DESCRIPTION
**Pull request by fridde**
I don't think we still need the issue tracker-bullet point. It's rather obvious that issues should be reported via *Github Issues*

### CODE REVIEW

**Comment by Ocramius** [comment]
@fridde thanks!

**Comment by fridde** [comment]
Sorry to bother again, but the main website http://www.doctrine-project.org is riddled with links to JIRA.

Is there any repo for the website?

**Comment by stof** [comment]
@fridde I think it is https://github.com/doctrine/doctrine-website-sphinx

**Comment by Ocramius** [comment]
See https://github.com/doctrine/doctrine-website-sphinx

**Pull request merged**
